### ISSUE TITLE
Which no SQL provider should we use?

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#33] opened 2015-02-10 02:23 UTC
Mongo
Couch?

**Comment by frankhale** [comment] 2015-02-10 02:27
Duplicate of https://github.com/DIOS-Tech/BlueHarvest/issues/29

Let's have the discussion there since that is what that issue is for.

**Comment by frankhale** [comment] 2015-02-10 02:29
We can use any, doesn't matter to me. Let's talk about it on the database discussion issue.

**Closed** 2015-02-16 21:32 UTC
